apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: my-atlas-cluster
  namespace: atlas
spec:
  clusterServiceClassExternalName: mongodb-atlas-aws
  clusterServicePlanExternalName: M10
  parameters:
    cluster:
      providerSettings:
        regionName: EU_CENTRAL_1
      autoscaling:
        diskGBEnabled: false
      backupEnabled: false